[package]
name = "cargo-install-upgrade"
version = "0.2.3"
authors = ["hecal3 <hecal3@users.noreply.github.com>"]
keywords = ["cargo", "subcommand", "install", "upgrade"]
description = "Extends cargo to upgrade packages installed via 'cargo install'"

[[bin]]
name = "cargo-install-upgrade"

[dependencies]
semver = "0.5"
clap = "2.19"
serde_json = "0.8"
tempdir = "0.3"
log = { version = "*", optional = true }
env_logger = {version = "*", optional = true }
toml = { version = "0.2", default-features = false, features = ["serde"] }

[features]
default = []
logger = ["log", "env_logger"]
